#!/bin/bash
clear

press_enter()
{
    echo -en "\nPress Enter to continue"
    read
    clear
}

install()
{
	clear
	apt-get install gphoto2 ffmpeg vlc v4l2loopback-utils v4l2loopback-dkms -y
	echo ""
	press_enter
	config_menu
}

configure()
{
	clear
	cat /etc/modules > /etc/modules-orig
	echo dslr-webcam >> /etc/modules
	echo "# Module options for Video4Linux, needed for our DSLR Webcam
	alias dslr-webcam v4l2loopback
	options v4l2loopback exclusive_caps=1 max_buffers=2" >> /etc/modprobe.d/dslr-webcam.conf
	clear
	echo Setup now complete. System restart required. 
	press_enter
	restart
}

restart()
{
	 reboot
}

install_menu()
{
	clear
	until [ "$selection" = "n" ]; do
		echo This needs to be run as ROOT
		echo ""
		echo "This will install the following packages and their dependencies:
		gphoto2
		ffmpeg
		vlc
		v4l2loopback
		mencoder
	"
		echo -n "Would you like to continue? [Y/n] "
		read selection
		echo ""
		case $selection in
			y|Y|"") install ; press_enter ;;
			n|N) exit ; clear ;;
			*) echo "Please enter 'y' or 'n'" ; press_enter
		esac
	done
}

config_menu()
{
	clear
	until [ "$selection" = "n" ]; do
		echo "Now we will configure the v4l2loopback module to be loaded at each boot
	"
		echo -n "Would you like to continue? [Y/n] "
		read selection
		echo ""
		case $selection in
			y|Y|"") configure ; press_enter ;;
			n|N) exit ; clear ;;
			*) echo "Please enter 'y' or 'n'" ; press_enter
		esac
	done
}

install_menu
