#!/bin/bash
clear
echo Enter video port number.
read PORT

gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video$PORT &

sleep 5

vlc v4l2:///dev/video$PORT
